version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=username
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080
    networks:
      - dockernet
    restart: unless-stopped
    command: start-dev

networks:
  dockernet:
    external: true

